# Generated by Django 5.0.6 on 2024-05-18 12:47

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from django.conf import settings

def create_attendance_group(apps, schema_editor):
    """
    Create attendance account group if not exists `settings.ATTENDANCE_ACCOUNT_GROUP`
    with add_attendance permission.
    """
    Group.objects.get_or_create(name=settings.ATTENDANCE_ACCOUNT_GROUP)

    ## add permission to group
    attendance_group = Group.objects.get(name=settings.ATTENDANCE_ACCOUNT_GROUP)
    attendance_group.permissions.add(
        Permission.objects.get(codename='add_attendance')
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_attendance_group)
    ]
