# Generated by Django 5.0.6 on 2024-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='generate_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='employee_id_cards'),
        ),
    ]
