# Generated by Django 5.0.6 on 2024-05-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_generate_id_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='generate_id_card',
            new_name='id_card_photo',
        ),
    ]
