# Generated by Django 5.0.6 on 2024-05-19 01:01

import apps.employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='1', upload_to='employee_photos', validators=[apps.employee.models.validate_image]),
            preserve_default=False,
        ),
    ]
